# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-12 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('matricula', models.CharField(max_length=9, verbose_name='Matricula')),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('resumo', models.TextField(blank=True, null=True, verbose_name='Resumo')),
                ('aluno', models.ManyToManyField(to='core.Aluno')),
            ],
            options={
                'ordering': ('nome',),
            },
        ),
    ]
